name: Build and Push Tools Docker Image

on:
  push:
    paths:
      - Dockerfile.buildtool
  pull_request:
      paths:
      - Dockerfile.buildtool
  workflow_dispatch:

jobs:
  build:
    name: Build & push docker image
    runs-on: ubuntu-latest
    env:
      IMG_NAME: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Debug
        run: |
          echo "github.ref -> {{ github.ref }}"
  
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: Dockerfile.buildtool